

###
POST http://127.0.0.1:3000/users/login
Content-Type: application/json

{
    "user_email": "userTeacher@gmail.com",
    "user_pass": "12345678"
}

###
POST http://127.0.0.1:3000/users/login
Content-Type: application/json

{
    "user_email": "Teststudent2@gmail.com",
    "user_pass": "12345678"
}

#####
GET http://127.0.0.1:3000/users/refresh
Content-Type: application/json
Authorization: token


###
POST http://127.0.0.1:3000/users/register
Content-Type: application/json
Authorization: token

{
    "user_name": "thisUserStudent2",
    "user_email": "Teststudent2@gmail.com",
    "user_pass": "12345678",
    "role": "readWrite",
    "user_adm_email": "userCreatorAdministrator@email.com",
    "user_adm_pass": "12345678"
}

###
GET http://127.0.0.1:3000/users/logout
Content-Type: application/json
#####
GET http://127.0.0.1:3000/posts
Content-Type: application/json


#####
GET  http://127.0.0.1:3000/posts/search?q=requis
Content-Type: application/json


#####
GET  http://127.0.0.1:3000/posts/696584d4094eb77398ccbd12
Content-Type: application/json


#####
POST http://127.0.0.1:3000/posts
Content-Type: application/json


{
    "user_name": "thisUserTeacher",
    "post_title": "Implementando arquivo de requisições http",
    "post_description": "Esse post é um teste para implementação de requisições http, isso deixa os testes mais rápidos e não necessita do POSTMAN",
    "post_videp_url": "https://aikdjkladjkjaksdj.com.br"
}

###
PUT http://127.0.0.1:3000/posts/696584d4094eb77398ccbd12
Content-Type: application/json

{
    "user_name": "MInecraft"
}

###
DELETE http://127.0.0.1:3000/posts/696584d4094eb77398ccbd12
Content-Type: application/json
