

### Teacher
POST http://127.0.0.1:3000/users/login
Content-Type: application/json

{
    "user_email": "thisUserIsTeacher@gmail.com",
    "user_pass": "12345678"
}

### Admin get
GET http://127.0.0.1:3000/users/search?q=thisUserIsTeacher
Content-Type: application/json

### Delete
DELETE  http://127.0.0.1:3000/users/69d6b81681d62ad789fe234f
Content-Type: application/json

### Admin
POST http://127.0.0.1:3000/users/login
Content-Type: application/json

{
    "user_email": "AdminUserFiap@gmail.com",
    "user_pass": "12345678"
}

### Student
POST http://127.0.0.1:3000/users/login
Content-Type: application/json

{
    "user_email": "thisUserIsStudent@gmail.com",
    "user_pass": "12345678"
}


### Admin create
POST http://127.0.0.1:3000/users/register
Content-Type: application/json

{
    "user_name": "Admin",
    "user_email": "AdminUserFiap@gmail.com",
    "user_pass": "12345678",
    "role": "userAdm"
}

### Teacher create
POST http://127.0.0.1:3000/users/register
Content-Type: application/json

{
    "user_name": "thisUserIsTeacher",
    "user_email": "thisUserIsTeacher@gmail.com",
    "user_pass": "12345678",
    "role": "readWrite"
}

### student create
POST http://127.0.0.1:3000/users/register
Content-Type: application/json

{
    "user_name": "thisUserIsStudent",
    "user_email": "thisUserIsStudent@gmail.com",
    "user_pass": "12345678",
    "role": "readOnly"
}


### Getting posts
GET http://127.0.0.1:3000/posts?page=1&amountOfPosts=2
Content-Type: application/json


### Search for posts
GET  http://127.0.0.1:3000/posts/search?q=requis
Content-Type: application/json


### Get one post
GET  http://127.0.0.1:3000/posts/69be0112521e5e61aa0f4257
Content-Type: application/json


### Creating Post 
POST http://127.0.0.1:3000/posts
Content-Type: application/json


{
    "user_name": "1",
    "post_title": "Implementando arquivo de requisições http",
    "post_description": "Esse post é um teste para implementação de requisições http.",
    "post_videp_url": "https://teacherVideo.com.br"
}

### Modifying Post 
PUT http://127.0.0.1:3000/posts/696584d4094eb77398ccbd12
Content-Type: application/json

{
    "user_name": "NewName"
}

### Delete Post
DELETE http://127.0.0.1:3000/posts/696584d4094eb77398ccbd12
Content-Type: application/json

### Logout User
GET http://127.0.0.1:3000/users/logout
Content-Type: application/json
